version: "3"
services:
  api:
    build: ./server
    ports:
      - "5001:5001"
    depends_on:
      - db
    restart: unless-stopped
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    restart: unless-stopped
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - client
    restart: unless-stopped

volumes:
    mongodb:
    

