version: "3"
services:
  api:
    build: ./server
    ports:
      - "5001:5001"
    depends_on:
      - db
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - client

volumes:
    mongodb:
    

